spring:
  application:
    name: verification
  profiles:
    default: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  third-party:
    base-url: http://localhost:${server.port}
  failure:
    free-probability: 0.40
    premium-probability: 0.10
  persistence:
    table-name: verification
    create-table-on-startup: true
  dynamodb:
    endpoint: http://localhost:8000
    region: us-east-1
    access-key: local
    secret-key: local
