spring:
  application:
    name: third-party

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - verificationId
      correlation:
        fields:
          - verificationId

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  failure:
    free-probability: 0.40
    premium-probability: 0.10
